# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  tags:
    - ugrad
  stage: build
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - if [ -f CMakeLists.txt ]; then cmake CMakeLists.txt; fi
    - make
  artifacts:
    paths:
      - prosim/prosim

test00:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 00 . prosim

test01:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 01 . prosim

test02:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 02 . prosim

test03:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 03 . prosim

test04:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 04 . prosim

test05:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 05 . prosim

test06:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 06 . prosim

test07:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 07 . prosim

test08:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 08 . prosim

test09:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 09 . prosim

test10:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 10 . prosim

test11:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 11 . prosim

test12:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 12 . prosim

test13:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 13 . prosim

test14:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 14 . prosim

test15:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 15 . prosim

test16:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 16 . prosim

test17:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 17 . prosim

test18:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 18 . prosim

test19:
  tags:
    - ugrad
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /NO_TEST/
  script:
    - cd prosim
    - ./tests/test.sh 19 . prosim
